---

# GitHub Actions
actions:
  - '.github/**/*.yml'

# http://tools.suckless.org/dmenu/
dmenu:
  - '.local/share/suckless/dmenu/**'

# Improvements or additions to documentation
documentation:
  - '**/*.md'
  - '.github/*.md'
  - '.github/LICENSE'
  - '.github/CODEOWNERS'
  - '.github/ISSUE_TEMPLATE/config.yml'
  - '.gitattributes'
  - '.config/vim/pack/**/README.md'

# http://dwm.suckless.org/
dwm:
  - '.local/share/suckless/dwm/**/*'

# This regards the .editorconfig file or settings
editorconfig:
  - '**/.editorconfig'

# This regards git
git:
  - '.config/git/**/*'
  - '.gitmodules'
  - '**/.gitattributes'
  - '**/.gitignore'

# Actually GitHub
github:
  - '.github/**/*'

# https://golang.org/
go:
  - '.local/bin/go/**/*'

# This regards JavaScript
js:
  - '**/*.js'

# This regards the Korn Shell
ksh:
  - '.config/ksh/kshrc'
  - '**/*.ksh'

# This regards the labeler automation
labeler:
  - '.github/labeler.yml'

# Has to do with Puffy
openbsd:
  - '**/openbsd/**/*'
  - '.config/doas/**/*'
  - '.config/xenodm/**/*'
  - '.config/ksh/kshrc'
  - '**/*.ksh'

# This regards the UNIX shell environment
shell:
  - '**/*.sh'
  - '**/*.ksh'
  - '.profile'
  - '.config/sh/shrc'
  - '.config/ksh/kshrc'

# GitHub sponsors
sponsor:
  - '.github/FUNDING.yml'

# http://st.suckless.org/
st:
  - '.local/share/suckless/st/**/*'

# Anything to do with a suckless.org tool
suckless:
  - '.local/share/suckless/dmenu/**/*'
  - '.local/share/suckless/dwm/**/*'
  - '.local/share/suckless/st/**/*'
  - '.local/share/suckless/surf/**/*'
  - '.local/share/suckless/tabbed/**/*'
  - '.local/share/suckless/**/*'
  - '**/*.config.h'
  - '**/*.config.def.h'

# http://surf.suckless.org/
surf:
  - '.local/share/suckless/surf/**/*'

# http://tools.suckless.org/tabbed/
tabbed:
  - '.local/share/suckless/tabbed/**/*'

# This needs a test case written
test:
  - '.github/workflows/testing.yml'

# This regards vim or vimscript
vim:
  - '.config/vim/exrc'
  - '.config/vim/vimrc'
  - '.config/vim/**/*'
  - '.config/vim/pack/**/*'
  - '**/*.vim'

# This regards Xorg or X11
x11:
  - '.config/X11/**/*'
  - '.config/X11/xdm/**/*'
