---

# GitHub Actions
actions: '.github/workflows/*.yml'

# http://tools.suckless.org/dmenu/
dmenu: '.dmenu/**'

# Improvements or additions to documentation
documentation:
  - '.github/*.yml'
  - '.github/*.md'
  - '.github/LICENSE'
  - '.github/CODEOWNERS'
  - '.github/ISSUE_TEMPLATE/*.yml'
  - '.github/ISSUE_TEMPLATE/*.md'
  - '.gitattributes'
  - '.vim/pack/*/start/README.md'

# http://dwm.suckless.org/
dwm: '.dwm/**'

# This regards the .editorconfig file or settings
editorconfig: '**/.editorconfig'

# Actually GitHub
github: '.github/**'

# This regards JavaScript
js: '**.js'

# Has to do with Puffy
openbsd:
  - '**/openbsd/**'
  - '.doas.conf'
  - '.xsetup'
  - '.kshrc'
  - '**.ksh'

# GitHub sponsors
sponsor: '.github/FUNDING.yml'

# http://st.suckless.org/
st: '.st/**'

# Anything to do with a suckless.org tool
suckless:
  - '.dmenu/**'
  - '.dwm/**'
  - '.st/**'
  - '.surf/**'
  - '.tabbed/**'
  - '**.config.h'
  - '**.config.def.h'

# http://surf.suckless.org/
surf: '.surf/**'

# http://tools.suckless.org/tabbed/
tabbed: '.tabbed/**'

# This needs a test case written
test: '.github/workflows/testing.yml'

# This regards vim or vimscript
vim:
  - '.vim/*'
  - '.vim/**/*'

# This affects Visual Studio (or VS-Code)
visual studio: '.vs/**'
