---

# Defines who can be requested to make a review
reviewers:

  # The default reviewers
  defaults:
    - repository-owners
    - core-contributors

  # Reviewer groups each of which has a list of GitHub usernames
  groups:

    # Users responsible for repo
    repository-owners:
      - yuri-norwood

    # Users with major contributions
    core-contributors:
      - yuri-norwood

  # Reviewers per author.
  # Keys are reviewees, each of which has an array of reviewers.
  per_author:

    # Core contributors need reviews from repo owners.
    core-contributors:
      - repository-owners

    # Repository owners need internal reviews.
    repository-owners:
      - repository-owners

# Keys are glob expressions.
# You can assign groups defined above as well as GitHub usernames.
files:

  # All files require owner review.
  '**':
    - repository-owners # group

options:

  # Don't add reviewers until the PR is ready.
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
    - WIP
