---

# Defines who can be requested to make a review
reviewers:

  # The default reviewers
  defaults:
    - repository-owners
    - core-contributors

  # Reviewer groups each of which has a list of GitHub usernames
  groups:

    # Users responsible for repo
    repository-owners:
      - yuri-norwood

    # Users with major contributions
    core-contributors:
      - yuri-norwood

  # Reviewers per author.
  # Keys are reviewees, each of which has an array of reviewers.
  per_author:

    # Core contributors need reviews from repo owners.
    core-contributors:
      - repository-owners

    # Repository owners need internal reviews.
    repository-owners:
      - repository-owners

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - repository-owners # group
  '**/*.js':
    - core-contributors # group
    - js-lovers # group
  '**/*.yml':
    - core-contributors # group
    - yamler # username
  '.github/**':
    - octopus # username
    - cat # username

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false

  # Randomly pick reviewers up to this number.
  # Do not set this option if you'd like to assign all matching reviewers.
  number_of_reviewers: 3
