#!/bin/sh

#
# Alias definitions
#

# Simplify directory listing
alias ls="ls -F"
alias la="ls -A"
alias ll="ls -l"

# Simplify directory creation
alias mkdir="mkdir -p"

# Simplify directory navigation
alias ..="cd .."

