"
" Vimrc - Vim Editor Configs
"
" Author:  Yuri Norwood
" See:     https://github/yuri-norwood/dotfiles
"

" Allow special characters and symbols
set encoding=utf-8 " do this before :scriptencoding
scriptencoding utf-8

" Allow XDG directories to be searched for runtime files
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

" Allow XDG directories to be searched for packages
set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

" Allow viminfo files to respect XDG directories
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo

" Allow spellfiles to respect XDG directories
call mkdir($XDG_DATA_HOME.'/vim/spell/', 'p', 0700)

" Prevent annoying flashes and beeps
set belloff=all

" Show commands while being typed
set showcmd

" Define preferred line width
set textwidth=80

" Define gutter size
set numberwidth=5

" Show line numbers but only if there's room
if &columns < (&textwidth + &numberwidth)
	set nonumber
else
	set number
endif

" Enable report message for all actions
set report=0

" Always show current file, ruler, mode, etc...
set laststatus=2

" Highlight all matches of a search phrase
set hlsearch

" Search incrementally and case insensitively (unless explicit capital letter)
set ignorecase
set smartcase
set incsearch

" Indent according to filetype / language syntax
set autoindent " this is safe to use with filetype based indenting
set tabstop=8
set softtabstop=0
set shiftwidth=8
set noexpandtab
filetype plugin indent on

" Allow backspace key to work as one would expect in the 21st century
set backspace=indent,eol,start " allow backspace to cross lines
set whichwrap=b,s,<,>,[,]      " allow left/right arrows to cross lines

" Allow pressing tab to autocomplete vim commands
set wildmenu
set wildmode=longest:full,full

" Allow mouse copy to ignore line numbers
set mouse=a

" Allow mouse leftdrag / rightclick / middleclick to behave like a GUI
set mousemodel=popup_setpos

" Make mouse show as I-beam everywhere, since everything is text
set mouseshape=a:beam

" Show a rule at the end of the &textwidth
set colorcolumn=+1

" Allow collapsible regions
set foldmethod=marker

" Allow files to define custom rule to be edited by
set modeline
set modelines=5

" Wrap lines that span past the terminal window
set wrap
set linebreak
set nolist

" Enable spell checking (but ignore capitalization errors)
set spell
set spelllang=en_nz
set spellcapcheck=""

" Setup colourscheme
syntax on
colorscheme github

" Allow colours to work correctly, regardless of terminal
set t_Co=256
set t_ut=""
set termguicolors
set background=dark

" Disable parenthesis matching highlight, as it is is extremely annoying
let g:loaded_matchparen = 1

" Show tabs as special character, NOTE: listchars has a trailing space
set list
set listchars=tab:\|\ 
match Comment /\t/

" Allow special sequences to be collapsed inline
set conceallevel =1

" Ensure editor config plugin works with fugitive plugin
let g:EditorConfig_exclude_patterns = [ 'fugitive://.*' ]

" Configure pangloss/javascript
let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_ngdoc = 1
let g:javascript_plugin_flow  = 1

" Configure plasticboy/vim-markdown
let g:vim_markdown_fenced_language           = [ 'editorconfig=dosini' ]
let g:vim_markdown_math                      = 1
let g:vim_markdown_strikethrough             = 1
let g:vim_markdown_new_list_item_indent      = 2
let g:vim_markdown_no_extensions_in_markdown = 1
let g:vim_markdown_autowrite                 = 1
let g:vim_markdown_edit_url_in               = 'vsplit'

