#!/bin/sh

#
# Session shell configuration
#

# Helper to calculate PS1
_PS1_DIR() {
	case "$PWD" in
		"$HOME") echo "~"          ;;
		"/")     echo "/"          ;;
		*)       echo "${PWD##*/}" ;;
	esac
}

# Set the prompt to the current directory and a dollar sign
export PS1='$(_PS1_DIR) $ '

# Catch session shell
case "$0" in
	# Include kshrc in interactive ksh sessions, within
	# the confines of this case we can assume ksh syntax.
	*ksh*)
		# shellcheck disable=SC2039,SC3010 source=/dev/null
		if [[ $- = *i* ]] && [ "${KSHRC}" ]
		then
			. "${KSHRC}"
		fi
	;;
esac

