---

# This file defines testing actions
name: linting

# Test whenever there is a push or a pull request opened
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Define a job for each test group
jobs:
  # This job checks that all config tests pass
  configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test Foo
        run: echo "Testing foo..."
      - uses: actions/checkout@v1
      - name: Test .xinitrc
        run: |
          echo "Test... that the profile is included..."
          grep -E "^\. ~/.profile" .xinitrc
      - uses: actions/checkout@v1
      - name: Test .xinitrc
        run: |
          echo "Test... that dwm is exec-ed, unless dwm is not found and uname returns 'OpenBSD'..."
          grep -E "^exec dwm"
      - uses: actions/checkout@v1
      - name: Test .xinitrc
        run: |
          echo "Test... that fvwm is exec-ed if dwm is not installed and uname returns 'OpenBSD'..."
      - uses: actions/checkout@v1
      - name: Test .xsession
        run: |
          echo "Test... that the xinitrc file is included..."
          grep -E "^\. ~/.xinitrc" .xsession
      - uses: actions/checkout@v1
      - name: Test xsetup
        run: |
          echo "Test... that xsetroot is called..."
          grep -E "^xsetroot" .xsetup

  # This job checks that all script tests pass
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test Foo
        run: echo "Testing foo..."
