---

# This file defines testing actions
name: testing

# Test whenever there is a push or a pull request opened
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Define a job for each test group
jobs:
  # This job checks that all config tests pass
  configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test Foo
        run: echo "Testing foo..."

      # Test shellcheck config syntax is valid
      # ---
      # This ensures that only valid shellcheck directives
      # are disabled via the shellcheck config file.
      - uses: actions/checkout@v1
      - name: Test .shellcheckrc
        run: |
          echo "Testing that all lines match regex..."
          grep -E '^disable=SC\d+$' .shellcheckrc

  # This job checks that all script tests pass
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test Foo
        run: echo "Testing foo..."
