---

# This file defines automation actions
name: Weekly

# Run automations weekly
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

# Define a job for each automatic task
jobs:

  # This job updates all submodules
  update-submodules:
    runs-on: ubuntu-latest
    steps:

      # Checkout main code
      - uses: actions/checkout@v2
        with:
          ref: main

      # Set environment variables to allow configuration
      - name: Set env
        run: |
          echo "GITHUB_NEW_BRANCH=000-git-submodule-auto-update" >> $GITHUB_ENV

      # Create new branch and push to remote
      - name: Push branch
        run: |
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout -b "${{ env.GITHUB_NEW_BRANCH }}"
          git push -u origin "${{ env.GITHUB_NEW_BRANCH }}"

      # Run update
      - name: Update modules
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive git pull origin master

      # Auto commit changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated submodules
          commit_user_name: Yuri Norwood
          commit_user_email: 76186754+yuri-norwood@users.noreply.github.com
          commit_author: Yuri Norwood <76186754+yuri-norwood@users.noreply.github.com>
          branch: ${{ env.GITHUB_NEW_BRANCH }}

      # Create new pull request
      - name: Create Pull Request
        uses: thomaseizinger/create-pull-request@1.1.0
        with:
          base: main
          head: ${{ env.GITHUB_NEW_BRANCH }}
          title: "[GIT-000]: Update Submodules"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
